#
#   Copyright (c) 2021, 2121, trustbe and/or its affiliates. All rights reserved.
#   TRUSTBE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

.PHONY: install

.PHONY: install
install:
	@flutter pub get
	@flutter build web

setup:
	yarn set version berry

pub:
	yarn build && yarn npm publish