#
#   Copyright (c) 2021, 2121, ducesoft and/or its affiliates. All rights reserved.
#   DUCESOFT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

.PHONY: install

.PHONY: install
install:
	@flutter pub get
	@flutter build web

setup:
	yarn set version berry