// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ProtobufTest.proto

package com.be.mesh.client.codec.proto;

public final class ProtobufTest {
  private ProtobufTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PsiExecuteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.be.mesh.client.codec.proto.PsiExecuteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sourcePartnerCode = 1;</code>
     * @return The sourcePartnerCode.
     */
    java.lang.String getSourcePartnerCode();
    /**
     * <code>string sourcePartnerCode = 1;</code>
     * @return The bytes for sourcePartnerCode.
     */
    com.google.protobuf.ByteString
        getSourcePartnerCodeBytes();

    /**
     * <code>string taskId = 2;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <code>string taskId = 2;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>string authorityCode = 3;</code>
     * @return The authorityCode.
     */
    java.lang.String getAuthorityCode();
    /**
     * <code>string authorityCode = 3;</code>
     * @return The bytes for authorityCode.
     */
    com.google.protobuf.ByteString
        getAuthorityCodeBytes();

    /**
     * <code>string index = 4;</code>
     * @return The index.
     */
    java.lang.String getIndex();
    /**
     * <code>string index = 4;</code>
     * @return The bytes for index.
     */
    com.google.protobuf.ByteString
        getIndexBytes();

    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @return A list containing the encodeData.
     */
    java.util.List<com.google.protobuf.ByteString> getEncodeDataList();
    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @return The count of encodeData.
     */
    int getEncodeDataCount();
    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @param index The index of the element to return.
     * @return The encodeData at the given index.
     */
    com.google.protobuf.ByteString getEncodeData(int index);
  }
  /**
   * Protobuf type {@code com.be.mesh.client.codec.proto.PsiExecuteRequest}
   */
  public static final class PsiExecuteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.be.mesh.client.codec.proto.PsiExecuteRequest)
      PsiExecuteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PsiExecuteRequest.newBuilder() to construct.
    private PsiExecuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PsiExecuteRequest() {
      sourcePartnerCode_ = "";
      taskId_ = "";
      authorityCode_ = "";
      index_ = "";
      encodeData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PsiExecuteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PsiExecuteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sourcePartnerCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              authorityCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              index_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                encodeData_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              encodeData_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          encodeData_ = java.util.Collections.unmodifiableList(encodeData_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.class, com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.Builder.class);
    }

    public static final int SOURCEPARTNERCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object sourcePartnerCode_;
    /**
     * <code>string sourcePartnerCode = 1;</code>
     * @return The sourcePartnerCode.
     */
    @java.lang.Override
    public java.lang.String getSourcePartnerCode() {
      java.lang.Object ref = sourcePartnerCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourcePartnerCode_ = s;
        return s;
      }
    }
    /**
     * <code>string sourcePartnerCode = 1;</code>
     * @return The bytes for sourcePartnerCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSourcePartnerCodeBytes() {
      java.lang.Object ref = sourcePartnerCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourcePartnerCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string taskId = 2;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 2;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORITYCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object authorityCode_;
    /**
     * <code>string authorityCode = 3;</code>
     * @return The authorityCode.
     */
    @java.lang.Override
    public java.lang.String getAuthorityCode() {
      java.lang.Object ref = authorityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string authorityCode = 3;</code>
     * @return The bytes for authorityCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorityCodeBytes() {
      java.lang.Object ref = authorityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_FIELD_NUMBER = 4;
    private volatile java.lang.Object index_;
    /**
     * <code>string index = 4;</code>
     * @return The index.
     */
    @java.lang.Override
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      }
    }
    /**
     * <code>string index = 4;</code>
     * @return The bytes for index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCODEDATA_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> encodeData_;
    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @return A list containing the encodeData.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getEncodeDataList() {
      return encodeData_;
    }
    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @return The count of encodeData.
     */
    public int getEncodeDataCount() {
      return encodeData_.size();
    }
    /**
     * <code>repeated bytes encodeData = 5;</code>
     * @param index The index of the element to return.
     * @return The encodeData at the given index.
     */
    public com.google.protobuf.ByteString getEncodeData(int index) {
      return encodeData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourcePartnerCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourcePartnerCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorityCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, authorityCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(index_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, index_);
      }
      for (int i = 0; i < encodeData_.size(); i++) {
        output.writeBytes(5, encodeData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourcePartnerCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourcePartnerCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authorityCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, authorityCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(index_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, index_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < encodeData_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encodeData_.get(i));
        }
        size += dataSize;
        size += 1 * getEncodeDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest)) {
        return super.equals(obj);
      }
      com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest other = (com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest) obj;

      if (!getSourcePartnerCode()
          .equals(other.getSourcePartnerCode())) return false;
      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getAuthorityCode()
          .equals(other.getAuthorityCode())) return false;
      if (!getIndex()
          .equals(other.getIndex())) return false;
      if (!getEncodeDataList()
          .equals(other.getEncodeDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCEPARTNERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getSourcePartnerCode().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + AUTHORITYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorityCode().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
      if (getEncodeDataCount() > 0) {
        hash = (37 * hash) + ENCODEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getEncodeDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.be.mesh.client.codec.proto.PsiExecuteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.be.mesh.client.codec.proto.PsiExecuteRequest)
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.class, com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.Builder.class);
      }

      // Construct using com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sourcePartnerCode_ = "";

        taskId_ = "";

        authorityCode_ = "";

        index_ = "";

        encodeData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor;
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest getDefaultInstanceForType() {
        return com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest build() {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest buildPartial() {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest result = new com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest(this);
        int from_bitField0_ = bitField0_;
        result.sourcePartnerCode_ = sourcePartnerCode_;
        result.taskId_ = taskId_;
        result.authorityCode_ = authorityCode_;
        result.index_ = index_;
        if (((bitField0_ & 0x00000001) != 0)) {
          encodeData_ = java.util.Collections.unmodifiableList(encodeData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.encodeData_ = encodeData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest) {
          return mergeFrom((com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest other) {
        if (other == com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest.getDefaultInstance()) return this;
        if (!other.getSourcePartnerCode().isEmpty()) {
          sourcePartnerCode_ = other.sourcePartnerCode_;
          onChanged();
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getAuthorityCode().isEmpty()) {
          authorityCode_ = other.authorityCode_;
          onChanged();
        }
        if (!other.getIndex().isEmpty()) {
          index_ = other.index_;
          onChanged();
        }
        if (!other.encodeData_.isEmpty()) {
          if (encodeData_.isEmpty()) {
            encodeData_ = other.encodeData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEncodeDataIsMutable();
            encodeData_.addAll(other.encodeData_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sourcePartnerCode_ = "";
      /**
       * <code>string sourcePartnerCode = 1;</code>
       * @return The sourcePartnerCode.
       */
      public java.lang.String getSourcePartnerCode() {
        java.lang.Object ref = sourcePartnerCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourcePartnerCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourcePartnerCode = 1;</code>
       * @return The bytes for sourcePartnerCode.
       */
      public com.google.protobuf.ByteString
          getSourcePartnerCodeBytes() {
        java.lang.Object ref = sourcePartnerCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourcePartnerCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourcePartnerCode = 1;</code>
       * @param value The sourcePartnerCode to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePartnerCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourcePartnerCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sourcePartnerCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourcePartnerCode() {
        
        sourcePartnerCode_ = getDefaultInstance().getSourcePartnerCode();
        onChanged();
        return this;
      }
      /**
       * <code>string sourcePartnerCode = 1;</code>
       * @param value The bytes for sourcePartnerCode to set.
       * @return This builder for chaining.
       */
      public Builder setSourcePartnerCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourcePartnerCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>string taskId = 2;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskId = 2;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 2;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 2;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authorityCode_ = "";
      /**
       * <code>string authorityCode = 3;</code>
       * @return The authorityCode.
       */
      public java.lang.String getAuthorityCode() {
        java.lang.Object ref = authorityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string authorityCode = 3;</code>
       * @return The bytes for authorityCode.
       */
      public com.google.protobuf.ByteString
          getAuthorityCodeBytes() {
        java.lang.Object ref = authorityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string authorityCode = 3;</code>
       * @param value The authorityCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authorityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string authorityCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorityCode() {
        
        authorityCode_ = getDefaultInstance().getAuthorityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string authorityCode = 3;</code>
       * @param value The bytes for authorityCode to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authorityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object index_ = "";
      /**
       * <code>string index = 4;</code>
       * @return The index.
       */
      public java.lang.String getIndex() {
        java.lang.Object ref = index_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          index_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string index = 4;</code>
       * @return The bytes for index.
       */
      public com.google.protobuf.ByteString
          getIndexBytes() {
        java.lang.Object ref = index_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          index_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string index = 4;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = getDefaultInstance().getIndex();
        onChanged();
        return this;
      }
      /**
       * <code>string index = 4;</code>
       * @param value The bytes for index to set.
       * @return This builder for chaining.
       */
      public Builder setIndexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        index_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> encodeData_ = java.util.Collections.emptyList();
      private void ensureEncodeDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          encodeData_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encodeData_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @return A list containing the encodeData.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncodeDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(encodeData_) : encodeData_;
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @return The count of encodeData.
       */
      public int getEncodeDataCount() {
        return encodeData_.size();
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @param index The index of the element to return.
       * @return The encodeData at the given index.
       */
      public com.google.protobuf.ByteString getEncodeData(int index) {
        return encodeData_.get(index);
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @param index The index to set the value at.
       * @param value The encodeData to set.
       * @return This builder for chaining.
       */
      public Builder setEncodeData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodeDataIsMutable();
        encodeData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @param value The encodeData to add.
       * @return This builder for chaining.
       */
      public Builder addEncodeData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodeDataIsMutable();
        encodeData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @param values The encodeData to add.
       * @return This builder for chaining.
       */
      public Builder addAllEncodeData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncodeDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encodeData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodeData = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodeData() {
        encodeData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.be.mesh.client.codec.proto.PsiExecuteRequest)
    }

    // @@protoc_insertion_point(class_scope:com.be.mesh.client.codec.proto.PsiExecuteRequest)
    private static final com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest();
    }

    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PsiExecuteRequest>
        PARSER = new com.google.protobuf.AbstractParser<PsiExecuteRequest>() {
      @java.lang.Override
      public PsiExecuteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PsiExecuteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PsiExecuteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PsiExecuteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PsiExecuteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.be.mesh.client.codec.proto.PsiExecuteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stage = 1;</code>
     * @return The stage.
     */
    java.lang.String getStage();
    /**
     * <code>string stage = 1;</code>
     * @return The bytes for stage.
     */
    com.google.protobuf.ByteString
        getStageBytes();

    /**
     * <code>string taskId = 2;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <code>string taskId = 2;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>repeated bytes maskData = 3;</code>
     * @return A list containing the maskData.
     */
    java.util.List<com.google.protobuf.ByteString> getMaskDataList();
    /**
     * <code>repeated bytes maskData = 3;</code>
     * @return The count of maskData.
     */
    int getMaskDataCount();
    /**
     * <code>repeated bytes maskData = 3;</code>
     * @param index The index of the element to return.
     * @return The maskData at the given index.
     */
    com.google.protobuf.ByteString getMaskData(int index);

    /**
     * <code>repeated bytes encoders = 4;</code>
     * @return A list containing the encoders.
     */
    java.util.List<com.google.protobuf.ByteString> getEncodersList();
    /**
     * <code>repeated bytes encoders = 4;</code>
     * @return The count of encoders.
     */
    int getEncodersCount();
    /**
     * <code>repeated bytes encoders = 4;</code>
     * @param index The index of the element to return.
     * @return The encoders at the given index.
     */
    com.google.protobuf.ByteString getEncoders(int index);
  }
  /**
   * Protobuf type {@code com.be.mesh.client.codec.proto.PsiExecuteResponse}
   */
  public static final class PsiExecuteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.be.mesh.client.codec.proto.PsiExecuteResponse)
      PsiExecuteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PsiExecuteResponse.newBuilder() to construct.
    private PsiExecuteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PsiExecuteResponse() {
      stage_ = "";
      taskId_ = "";
      maskData_ = java.util.Collections.emptyList();
      encoders_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PsiExecuteResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PsiExecuteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stage_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                maskData_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              maskData_.add(input.readBytes());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                encoders_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              encoders_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          maskData_ = java.util.Collections.unmodifiableList(maskData_); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          encoders_ = java.util.Collections.unmodifiableList(encoders_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.class, com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.Builder.class);
    }

    public static final int STAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object stage_;
    /**
     * <code>string stage = 1;</code>
     * @return The stage.
     */
    @java.lang.Override
    public java.lang.String getStage() {
      java.lang.Object ref = stage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stage_ = s;
        return s;
      }
    }
    /**
     * <code>string stage = 1;</code>
     * @return The bytes for stage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStageBytes() {
      java.lang.Object ref = stage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKID_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string taskId = 2;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 2;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASKDATA_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> maskData_;
    /**
     * <code>repeated bytes maskData = 3;</code>
     * @return A list containing the maskData.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getMaskDataList() {
      return maskData_;
    }
    /**
     * <code>repeated bytes maskData = 3;</code>
     * @return The count of maskData.
     */
    public int getMaskDataCount() {
      return maskData_.size();
    }
    /**
     * <code>repeated bytes maskData = 3;</code>
     * @param index The index of the element to return.
     * @return The maskData at the given index.
     */
    public com.google.protobuf.ByteString getMaskData(int index) {
      return maskData_.get(index);
    }

    public static final int ENCODERS_FIELD_NUMBER = 4;
    private java.util.List<com.google.protobuf.ByteString> encoders_;
    /**
     * <code>repeated bytes encoders = 4;</code>
     * @return A list containing the encoders.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getEncodersList() {
      return encoders_;
    }
    /**
     * <code>repeated bytes encoders = 4;</code>
     * @return The count of encoders.
     */
    public int getEncodersCount() {
      return encoders_.size();
    }
    /**
     * <code>repeated bytes encoders = 4;</code>
     * @param index The index of the element to return.
     * @return The encoders at the given index.
     */
    public com.google.protobuf.ByteString getEncoders(int index) {
      return encoders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stage_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
      }
      for (int i = 0; i < maskData_.size(); i++) {
        output.writeBytes(3, maskData_.get(i));
      }
      for (int i = 0; i < encoders_.size(); i++) {
        output.writeBytes(4, encoders_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stage_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < maskData_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(maskData_.get(i));
        }
        size += dataSize;
        size += 1 * getMaskDataList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < encoders_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encoders_.get(i));
        }
        size += dataSize;
        size += 1 * getEncodersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse)) {
        return super.equals(obj);
      }
      com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse other = (com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse) obj;

      if (!getStage()
          .equals(other.getStage())) return false;
      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getMaskDataList()
          .equals(other.getMaskDataList())) return false;
      if (!getEncodersList()
          .equals(other.getEncodersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStage().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      if (getMaskDataCount() > 0) {
        hash = (37 * hash) + MASKDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMaskDataList().hashCode();
      }
      if (getEncodersCount() > 0) {
        hash = (37 * hash) + ENCODERS_FIELD_NUMBER;
        hash = (53 * hash) + getEncodersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.be.mesh.client.codec.proto.PsiExecuteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.be.mesh.client.codec.proto.PsiExecuteResponse)
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.class, com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.Builder.class);
      }

      // Construct using com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stage_ = "";

        taskId_ = "";

        maskData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        encoders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.be.mesh.client.codec.proto.ProtobufTest.internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor;
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse getDefaultInstanceForType() {
        return com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse build() {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse buildPartial() {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse result = new com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse(this);
        int from_bitField0_ = bitField0_;
        result.stage_ = stage_;
        result.taskId_ = taskId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          maskData_ = java.util.Collections.unmodifiableList(maskData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.maskData_ = maskData_;
        if (((bitField0_ & 0x00000002) != 0)) {
          encoders_ = java.util.Collections.unmodifiableList(encoders_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.encoders_ = encoders_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse) {
          return mergeFrom((com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse other) {
        if (other == com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse.getDefaultInstance()) return this;
        if (!other.getStage().isEmpty()) {
          stage_ = other.stage_;
          onChanged();
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.maskData_.isEmpty()) {
          if (maskData_.isEmpty()) {
            maskData_ = other.maskData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMaskDataIsMutable();
            maskData_.addAll(other.maskData_);
          }
          onChanged();
        }
        if (!other.encoders_.isEmpty()) {
          if (encoders_.isEmpty()) {
            encoders_ = other.encoders_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEncodersIsMutable();
            encoders_.addAll(other.encoders_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stage_ = "";
      /**
       * <code>string stage = 1;</code>
       * @return The stage.
       */
      public java.lang.String getStage() {
        java.lang.Object ref = stage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stage = 1;</code>
       * @return The bytes for stage.
       */
      public com.google.protobuf.ByteString
          getStageBytes() {
        java.lang.Object ref = stage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stage = 1;</code>
       * @param value The stage to set.
       * @return This builder for chaining.
       */
      public Builder setStage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStage() {
        
        stage_ = getDefaultInstance().getStage();
        onChanged();
        return this;
      }
      /**
       * <code>string stage = 1;</code>
       * @param value The bytes for stage to set.
       * @return This builder for chaining.
       */
      public Builder setStageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>string taskId = 2;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskId = 2;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 2;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 2;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> maskData_ = java.util.Collections.emptyList();
      private void ensureMaskDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          maskData_ = new java.util.ArrayList<com.google.protobuf.ByteString>(maskData_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @return A list containing the maskData.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getMaskDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(maskData_) : maskData_;
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @return The count of maskData.
       */
      public int getMaskDataCount() {
        return maskData_.size();
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @param index The index of the element to return.
       * @return The maskData at the given index.
       */
      public com.google.protobuf.ByteString getMaskData(int index) {
        return maskData_.get(index);
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @param index The index to set the value at.
       * @param value The maskData to set.
       * @return This builder for chaining.
       */
      public Builder setMaskData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMaskDataIsMutable();
        maskData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @param value The maskData to add.
       * @return This builder for chaining.
       */
      public Builder addMaskData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMaskDataIsMutable();
        maskData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @param values The maskData to add.
       * @return This builder for chaining.
       */
      public Builder addAllMaskData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureMaskDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maskData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes maskData = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaskData() {
        maskData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> encoders_ = java.util.Collections.emptyList();
      private void ensureEncodersIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          encoders_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encoders_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @return A list containing the encoders.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncodersList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(encoders_) : encoders_;
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @return The count of encoders.
       */
      public int getEncodersCount() {
        return encoders_.size();
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @param index The index of the element to return.
       * @return The encoders at the given index.
       */
      public com.google.protobuf.ByteString getEncoders(int index) {
        return encoders_.get(index);
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @param index The index to set the value at.
       * @param value The encoders to set.
       * @return This builder for chaining.
       */
      public Builder setEncoders(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodersIsMutable();
        encoders_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @param value The encoders to add.
       * @return This builder for chaining.
       */
      public Builder addEncoders(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodersIsMutable();
        encoders_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @param values The encoders to add.
       * @return This builder for chaining.
       */
      public Builder addAllEncoders(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncodersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encoders_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encoders = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncoders() {
        encoders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.be.mesh.client.codec.proto.PsiExecuteResponse)
    }

    // @@protoc_insertion_point(class_scope:com.be.mesh.client.codec.proto.PsiExecuteResponse)
    private static final com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse();
    }

    public static com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PsiExecuteResponse>
        PARSER = new com.google.protobuf.AbstractParser<PsiExecuteResponse>() {
      @java.lang.Override
      public PsiExecuteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PsiExecuteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PsiExecuteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PsiExecuteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.be.mesh.client.codec.proto.ProtobufTest.PsiExecuteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/ProtobufTest.proto\022\036com.be.mesh." +
      "client.codec.proto\"x\n\021PsiExecuteRequest\022" +
      "\031\n\021sourcePartnerCode\030\001 \001(\t\022\016\n\006taskId\030\002 \001" +
      "(\t\022\025\n\rauthorityCode\030\003 \001(\t\022\r\n\005index\030\004 \001(\t" +
      "\022\022\n\nencodeData\030\005 \003(\014\"W\n\022PsiExecuteRespon" +
      "se\022\r\n\005stage\030\001 \001(\t\022\016\n\006taskId\030\002 \001(\t\022\020\n\010mas" +
      "kData\030\003 \003(\014\022\020\n\010encoders\030\004 \003(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_be_mesh_client_codec_proto_PsiExecuteRequest_descriptor,
        new java.lang.String[] { "SourcePartnerCode", "TaskId", "AuthorityCode", "Index", "EncodeData", });
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_be_mesh_client_codec_proto_PsiExecuteResponse_descriptor,
        new java.lang.String[] { "Stage", "TaskId", "MaskData", "Encoders", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
