// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: proto/ProtobufTest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PsiExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePartnerCode string   `protobuf:"bytes,1,opt,name=sourcePartnerCode,proto3" json:"sourcePartnerCode,omitempty"`
	TaskId            string   `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	AuthorityCode     string   `protobuf:"bytes,3,opt,name=authorityCode,proto3" json:"authorityCode,omitempty"`
	Index             string   `protobuf:"bytes,4,opt,name=index,proto3" json:"index,omitempty"`
	EncodeData        [][]byte `protobuf:"bytes,5,rep,name=encodeData,proto3" json:"encodeData,omitempty"`
}

func (x *PsiExecuteRequest) Reset() {
	*x = PsiExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ProtobufTest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PsiExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsiExecuteRequest) ProtoMessage() {}

func (x *PsiExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProtobufTest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsiExecuteRequest.ProtoReflect.Descriptor instead.
func (*PsiExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ProtobufTest_proto_rawDescGZIP(), []int{0}
}

func (x *PsiExecuteRequest) GetSourcePartnerCode() string {
	if x != nil {
		return x.SourcePartnerCode
	}
	return ""
}

func (x *PsiExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PsiExecuteRequest) GetAuthorityCode() string {
	if x != nil {
		return x.AuthorityCode
	}
	return ""
}

func (x *PsiExecuteRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *PsiExecuteRequest) GetEncodeData() [][]byte {
	if x != nil {
		return x.EncodeData
	}
	return nil
}

type PsiExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage    string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	TaskId   string   `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	MaskData [][]byte `protobuf:"bytes,3,rep,name=maskData,proto3" json:"maskData,omitempty"`
	Encoders [][]byte `protobuf:"bytes,4,rep,name=encoders,proto3" json:"encoders,omitempty"`
}

func (x *PsiExecuteResponse) Reset() {
	*x = PsiExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ProtobufTest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PsiExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsiExecuteResponse) ProtoMessage() {}

func (x *PsiExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProtobufTest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsiExecuteResponse.ProtoReflect.Descriptor instead.
func (*PsiExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ProtobufTest_proto_rawDescGZIP(), []int{1}
}

func (x *PsiExecuteResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PsiExecuteResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PsiExecuteResponse) GetMaskData() [][]byte {
	if x != nil {
		return x.MaskData
	}
	return nil
}

func (x *PsiExecuteResponse) GetEncoders() [][]byte {
	if x != nil {
		return x.Encoders
	}
	return nil
}

var File_proto_ProtobufTest_proto protoreflect.FileDescriptor

var file_proto_ProtobufTest_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x54, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x6f, 0x6d, 0x2e,
	0x62, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x11, 0x50,
	0x73, 0x69, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x11, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x7a, 0x0a, 0x12, 0x50, 0x73, 0x69, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x73, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x61, 0x73, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x73, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ProtobufTest_proto_rawDescOnce sync.Once
	file_proto_ProtobufTest_proto_rawDescData = file_proto_ProtobufTest_proto_rawDesc
)

func file_proto_ProtobufTest_proto_rawDescGZIP() []byte {
	file_proto_ProtobufTest_proto_rawDescOnce.Do(func() {
		file_proto_ProtobufTest_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ProtobufTest_proto_rawDescData)
	})
	return file_proto_ProtobufTest_proto_rawDescData
}

var file_proto_ProtobufTest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ProtobufTest_proto_goTypes = []interface{}{
	(*PsiExecuteRequest)(nil),  // 0: com.be.mesh.client.codec.proto.PsiExecuteRequest
	(*PsiExecuteResponse)(nil), // 1: com.be.mesh.client.codec.proto.PsiExecuteResponse
}
var file_proto_ProtobufTest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ProtobufTest_proto_init() }
func file_proto_ProtobufTest_proto_init() {
	if File_proto_ProtobufTest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ProtobufTest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PsiExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ProtobufTest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PsiExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ProtobufTest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ProtobufTest_proto_goTypes,
		DependencyIndexes: file_proto_ProtobufTest_proto_depIdxs,
		MessageInfos:      file_proto_ProtobufTest_proto_msgTypes,
	}.Build()
	File_proto_ProtobufTest_proto = out.File
	file_proto_ProtobufTest_proto_rawDesc = nil
	file_proto_ProtobufTest_proto_goTypes = nil
	file_proto_ProtobufTest_proto_depIdxs = nil
}
