#
#   Copyright (c) 2021, 2121, trustbe and/or its affiliates. All rights reserved.
#   TRUSTBE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

include ../../Makefile

.PHONY: pub

.PHONY: pub
pub: setenv
	cargo install

