/*
* Copyright (c) 2000, 2099, ducesoft and/or its affiliates. All rights reserved.
* DUCESOFT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
*
*
 */

// Code generated by mesh; DO NOT EDIT.

package raft

import (
	"context"
	"strings"

	"github.com/be-io/mesh/client/golang/cause"
	"github.com/be-io/mesh/client/golang/macro"
	"github.com/be-io/mesh/client/golang/mpc"
	"github.com/be-io/mesh/client/golang/tool"
)

func init() {
	var service = &meshraftChannelMPS{mps: new(raftChannel)}
	var _ channel = service
	macro.Provide((*channel)(nil), service)

	var serviceSendMessage = &meshraftChannelSendMessageMPS{service: service}
	var _ mpc.Invoker = serviceSendMessage
	var _ macro.Caller = serviceSendMessage
	macro.Provide(mpc.IInvoker, serviceSendMessage)
	macro.Provide(macro.ICaller, serviceSendMessage)

	var serviceSendChunk = &meshraftChannelSendChunkMPS{service: service}
	var _ mpc.Invoker = serviceSendChunk
	var _ macro.Caller = serviceSendChunk
	macro.Provide(mpc.IInvoker, serviceSendChunk)
	macro.Provide(macro.ICaller, serviceSendChunk)

}

// meshraftChannelMPS is an implementation of raft.raftChannel
type meshraftChannelMPS struct {
	mps channel
}

func (that *meshraftChannelMPS) Att() *macro.Att {
	return &macro.Att{Name: macro.MeshSPI}
}

func (that *meshraftChannelMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: macro.MeshMPS}
}

// SendMessage send message with rpc.
// @MPI("mesh.raft.message")
func (that *meshraftChannelMPS) SendMessage(ctx context.Context, buff []byte) ([]byte, error) {
	return that.mps.SendMessage(ctx, buff)
}

// SendChunk send chunk with rpc.
// @MPI("mesh.raft.chunk")
func (that *meshraftChannelMPS) SendChunk(ctx context.Context, buff []byte) ([]byte, error) {
	return that.mps.SendChunk(ctx, buff)
}

type meshraftChannelSendMessageMPS struct {
	service channel
}

func (that *meshraftChannelSendMessageMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.raft.message", "${mesh.name}", tool.Name.Get())}
}
func (that *meshraftChannelSendMessageMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: "mesh.raft.message"}
}

func (that *meshraftChannelSendMessageMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(MeshchannelSendMessageParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.SendMessage(ctx, parameters.Buff)
}

func (that *meshraftChannelSendMessageMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*MeshchannelSendMessageParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.SendMessage(ctx, parameters.Buff)
}

type meshraftChannelSendChunkMPS struct {
	service channel
}

func (that *meshraftChannelSendChunkMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.raft.chunk", "${mesh.name}", tool.Name.Get())}
}
func (that *meshraftChannelSendChunkMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: "mesh.raft.chunk"}
}

func (that *meshraftChannelSendChunkMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(MeshchannelSendChunkParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.SendChunk(ctx, parameters.Buff)
}

func (that *meshraftChannelSendChunkMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*MeshchannelSendChunkParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.SendChunk(ctx, parameters.Buff)
}
