/*
* Copyright (c) 2000, 2023, trustbe and/or its affiliates. All rights reserved.
* TRUSTBE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
*
*
 */

// Code generated by mesh; DO NOT EDIT.

package proxy

import (
	"context"

	"github.com/be-io/mesh/client/golang/cause"
	"github.com/be-io/mesh/client/golang/macro"
	"github.com/be-io/mesh/client/golang/mpc"
	"github.com/be-io/mesh/client/golang/prsim"
)

func init() {
	var _ macro.Interface = new(meshEndpointMPI)
	macro.Provide((*prsim.Endpoint)(nil), &meshEndpointMPI{
		invoker: mpc.ServiceProxy.Reference(&macro.Rtt{}),
		methods: map[string]*macro.Method{
			"Fuzzy": {
				DeclaredKind: (*prsim.Endpoint)(nil),
				TName:        "prsim.Endpoint",
				Name:         "Fuzzy",
				Intype:       func() macro.Parameters { var parameters MeshEndpointFuzzyParameters; return &parameters },
				Retype:       func() macro.Returns { var returns MeshEndpointFuzzyReturns; return &returns },
				Inbound:      func() macro.Parameters { return new(MeshEndpointFuzzyParameters) },
				Outbound:     func() macro.Returns { return new(MeshEndpointFuzzyReturns) },
				MPI: &macro.MPIAnnotation{
					Meta: &macro.Rtt{Name: "${mesh.uname}"},
				},
			},
		},
	})
}

// meshEndpointMPI is an implementation of Endpoint
type meshEndpointMPI struct {
	invoker macro.Caller
	methods map[string]*macro.Method
}

func (that *meshEndpointMPI) Att() *macro.Att {
	return &macro.Att{Name: macro.MeshMPI}
}

func (that *meshEndpointMPI) Rtt() *macro.Rtt {
	return &macro.Rtt{Name: macro.MeshMPI}
}

func (that *meshEndpointMPI) GetMethods() map[string]*macro.Method {
	return that.methods
}

// Fuzzy call with generic param
// In multi returns, it's an array.
// @MPI("${mesh.uname}")
func (that *meshEndpointMPI) Fuzzy(ctx context.Context, buff []byte) ([]byte, error) {
	ret, err := that.invoker.Call(ctx, that.invoker, that.methods["Fuzzy"], buff)
	if nil != err {
		x := new(MeshEndpointFuzzyReturns)
		return x.Content, err
	}
	x, ok := ret.(*MeshEndpointFuzzyReturns)
	if ok {
		return x.Content, err
	}
	x = new(MeshEndpointFuzzyReturns)
	return x.Content, cause.Errorf("Cant resolve response ")
}

type MeshEndpointFuzzyParameters struct {
	Attachments map[string]string `index:"-1" json:"attachments" xml:"attachments" yaml:"attachments"`
	Buff        []byte            `index:"0" json:"buff" xml:"buff" yaml:"buff"`
}

func (that *MeshEndpointFuzzyParameters) GetKind() interface{} {
	return new(MeshEndpointFuzzyParameters)
}

func (that *MeshEndpointFuzzyParameters) GetArguments(ctx context.Context) []interface{} {
	var arguments []interface{}
	arguments = append(arguments, that.Buff)
	return arguments
}

func (that *MeshEndpointFuzzyParameters) SetArguments(ctx context.Context, arguments ...interface{}) {
	if len(arguments) > 0 {
		if len(arguments) > 0 && nil != arguments[0] {
			that.Buff = arguments[0].([]byte)
		}
	}
}

func (that *MeshEndpointFuzzyParameters) GetAttachments(ctx context.Context) map[string]string {
	return that.Attachments
}

func (that *MeshEndpointFuzzyParameters) SetAttachments(ctx context.Context, attachments map[string]string) {
	that.Attachments = attachments
}

type MeshEndpointFuzzyReturns struct {
	Code    string       `index:"0" json:"code" xml:"code" yaml:"code" comment:"Result code"`
	Message string       `index:"5" json:"message" xml:"message" yaml:"message" comment:"Result message"`
	Cause   *macro.Cause `index:"10" json:"cause" xml:"cause" yaml:"cause" comment:"Service cause stacktrace"`
	Content []byte       `index:"15" json:"content" xml:"content" yaml:"content"`
}

func (that *MeshEndpointFuzzyReturns) GetCode() string {
	return that.Code
}

func (that *MeshEndpointFuzzyReturns) SetCode(code string) {
	that.Code = code
}

func (that *MeshEndpointFuzzyReturns) GetMessage() string {
	return that.Message
}

func (that *MeshEndpointFuzzyReturns) SetMessage(message string) {
	that.Message = message
}

func (that *MeshEndpointFuzzyReturns) GetCause(ctx context.Context) *macro.Cause {
	return that.Cause
}

func (that *MeshEndpointFuzzyReturns) SetCause(ctx context.Context, cause *macro.Cause) {
	that.Cause = cause
}

func (that *MeshEndpointFuzzyReturns) GetContent(ctx context.Context) []interface{} {
	var arguments []interface{}
	arguments = append(arguments, that.Content)
	return arguments
}

func (that *MeshEndpointFuzzyReturns) SetContent(ctx context.Context, arguments ...interface{}) {
	if len(arguments) > 0 {
		if len(arguments) > 0 && nil != arguments[0] {
			that.Content = arguments[0].([]byte)
		}
	}
}
