/*
* Copyright (c) 2000, 2099, ducesoft and/or its affiliates. All rights reserved.
* DUCESOFT PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
*
*
 */

// Code generated by mesh; DO NOT EDIT.

package proxy

import (
	"context"
	"strings"
	"time"

	"github.com/be-io/mesh/client/golang/cause"
	"github.com/be-io/mesh/client/golang/macro"
	"github.com/be-io/mesh/client/golang/mpc"
	proxympx "github.com/be-io/mesh/client/golang/proxy"
	"github.com/be-io/mesh/client/golang/prsim"
	"github.com/be-io/mesh/client/golang/tool"
	"github.com/be-io/mesh/client/golang/types"
	prsimmps "github.com/be-io/mesh/plugin/prsim"
)

func init() {
	var service = &meshPRSITokenizerMPS{mps: new(prsimmps.PRSITokenizer)}
	var _ prsim.Tokenizer = service
	macro.Provide((*prsim.Tokenizer)(nil), service)

	var serviceApply = &meshPRSITokenizerApplyMPS{service: service}
	var _ mpc.Invoker = serviceApply
	var _ macro.Caller = serviceApply
	macro.Provide(mpc.IInvoker, serviceApply)
	macro.Provide(macro.ICaller, serviceApply)

	var serviceVerify = &meshPRSITokenizerVerifyMPS{service: service}
	var _ mpc.Invoker = serviceVerify
	var _ macro.Caller = serviceVerify
	macro.Provide(mpc.IInvoker, serviceVerify)
	macro.Provide(macro.ICaller, serviceVerify)

	var serviceQuickauth = &meshPRSITokenizerQuickauthMPS{service: service}
	var _ mpc.Invoker = serviceQuickauth
	var _ macro.Caller = serviceQuickauth
	macro.Provide(mpc.IInvoker, serviceQuickauth)
	macro.Provide(macro.ICaller, serviceQuickauth)

	var serviceGrant = &meshPRSITokenizerGrantMPS{service: service}
	var _ mpc.Invoker = serviceGrant
	var _ macro.Caller = serviceGrant
	macro.Provide(mpc.IInvoker, serviceGrant)
	macro.Provide(macro.ICaller, serviceGrant)

	var serviceAccept = &meshPRSITokenizerAcceptMPS{service: service}
	var _ mpc.Invoker = serviceAccept
	var _ macro.Caller = serviceAccept
	macro.Provide(mpc.IInvoker, serviceAccept)
	macro.Provide(macro.ICaller, serviceAccept)

	var serviceReject = &meshPRSITokenizerRejectMPS{service: service}
	var _ mpc.Invoker = serviceReject
	var _ macro.Caller = serviceReject
	macro.Provide(mpc.IInvoker, serviceReject)
	macro.Provide(macro.ICaller, serviceReject)

	var serviceAuthorize = &meshPRSITokenizerAuthorizeMPS{service: service}
	var _ mpc.Invoker = serviceAuthorize
	var _ macro.Caller = serviceAuthorize
	macro.Provide(mpc.IInvoker, serviceAuthorize)
	macro.Provide(macro.ICaller, serviceAuthorize)

	var serviceAuthenticate = &meshPRSITokenizerAuthenticateMPS{service: service}
	var _ mpc.Invoker = serviceAuthenticate
	var _ macro.Caller = serviceAuthenticate
	macro.Provide(mpc.IInvoker, serviceAuthenticate)
	macro.Provide(macro.ICaller, serviceAuthenticate)

	var serviceRefresh = &meshPRSITokenizerRefreshMPS{service: service}
	var _ mpc.Invoker = serviceRefresh
	var _ macro.Caller = serviceRefresh
	macro.Provide(mpc.IInvoker, serviceRefresh)
	macro.Provide(macro.ICaller, serviceRefresh)

}

// meshPRSITokenizerMPS is an implementation of prsim.PRSITokenizer
type meshPRSITokenizerMPS struct {
	mps *prsimmps.PRSITokenizer
}

func (that *meshPRSITokenizerMPS) Att() *macro.Att {
	return &macro.Att{Name: macro.MeshSPI}
}

func (that *meshPRSITokenizerMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: macro.MeshMPS}
}

// Apply
// @MPI("mesh.trust.apply")
func (that *meshPRSITokenizerMPS) Apply(ctx context.Context, kind string, duration time.Duration) (string, error) {
	return that.mps.Apply(ctx, kind, duration)
}

// Verify
// @MPI("mesh.trust.verify")
func (that *meshPRSITokenizerMPS) Verify(ctx context.Context, token string) (bool, error) {
	return that.mps.Verify(ctx, token)
}

// Quickauth OAuth2 quick authorize, contains grant code and code authorize.
// @MPI("mesh.oauth2.quickauth")
func (that *meshPRSITokenizerMPS) Quickauth(ctx context.Context, credential *types.Credential) (*types.AccessToken, error) {
	return that.mps.Quickauth(ctx, credential)
}

// Grant OAuth2 code grant.
// @MPI("mesh.oauth2.grant")
func (that *meshPRSITokenizerMPS) Grant(ctx context.Context, credential *types.Credential) (*types.AccessGrant, error) {
	return that.mps.Grant(ctx, credential)
}

// Accept OAuth2 accept grant code.
// @MPI("mesh.oauth2.accept")
func (that *meshPRSITokenizerMPS) Accept(ctx context.Context, code string) (*types.AccessCode, error) {
	return that.mps.Accept(ctx, code)
}

// Reject OAuth2 reject grant code.
// @MPI("mesh.oauth2.reject")
func (that *meshPRSITokenizerMPS) Reject(ctx context.Context, code string) error {
	return that.mps.Reject(ctx, code)
}

// Authorize OAuth2 code authorize.
// @MPI("mesh.oauth2.authorize")
func (that *meshPRSITokenizerMPS) Authorize(ctx context.Context, code string) (*types.AccessToken, error) {
	return that.mps.Authorize(ctx, code)
}

// Authenticate OAuth2 authenticate.
// @MPI("mesh.oauth2.authenticate")
func (that *meshPRSITokenizerMPS) Authenticate(ctx context.Context, token string) (*types.AccessID, error) {
	return that.mps.Authenticate(ctx, token)
}

// Refresh OAuth2 auth token refresh.
// @MPI("mesh.oauth2.refresh")
func (that *meshPRSITokenizerMPS) Refresh(ctx context.Context, token string) (*types.AccessToken, error) {
	return that.mps.Refresh(ctx, token)
}

type meshPRSITokenizerApplyMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerApplyMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.trust.apply", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerApplyMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.trust.apply", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerApplyMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerApplyParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Apply(ctx, parameters.Kind, parameters.Duration)
}

func (that *meshPRSITokenizerApplyMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerApplyParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Apply(ctx, parameters.Kind, parameters.Duration)
}

type meshPRSITokenizerVerifyMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerVerifyMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.trust.verify", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerVerifyMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.trust.verify", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerVerifyMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerVerifyParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Verify(ctx, parameters.Token)
}

func (that *meshPRSITokenizerVerifyMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerVerifyParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Verify(ctx, parameters.Token)
}

type meshPRSITokenizerQuickauthMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerQuickauthMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.quickauth", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerQuickauthMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.quickauth", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerQuickauthMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerQuickauthParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Quickauth(ctx, parameters.Credential)
}

func (that *meshPRSITokenizerQuickauthMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerQuickauthParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Quickauth(ctx, parameters.Credential)
}

type meshPRSITokenizerGrantMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerGrantMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.grant", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerGrantMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.grant", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerGrantMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerGrantParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Grant(ctx, parameters.Credential)
}

func (that *meshPRSITokenizerGrantMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerGrantParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Grant(ctx, parameters.Credential)
}

type meshPRSITokenizerAcceptMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerAcceptMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.accept", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerAcceptMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.accept", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerAcceptMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerAcceptParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Accept(ctx, parameters.Code)
}

func (that *meshPRSITokenizerAcceptMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerAcceptParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Accept(ctx, parameters.Code)
}

type meshPRSITokenizerRejectMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerRejectMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.reject", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerRejectMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.reject", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerRejectMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerRejectParameters)
	parameters.SetArguments(ctx, args...)
	return nil, that.service.Reject(ctx, parameters.Code)
}

func (that *meshPRSITokenizerRejectMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerRejectParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return nil, that.service.Reject(ctx, parameters.Code)
}

type meshPRSITokenizerAuthorizeMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerAuthorizeMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.authorize", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerAuthorizeMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.authorize", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerAuthorizeMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerAuthorizeParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Authorize(ctx, parameters.Code)
}

func (that *meshPRSITokenizerAuthorizeMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerAuthorizeParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Authorize(ctx, parameters.Code)
}

type meshPRSITokenizerAuthenticateMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerAuthenticateMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.authenticate", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerAuthenticateMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.authenticate", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerAuthenticateMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerAuthenticateParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Authenticate(ctx, parameters.Token)
}

func (that *meshPRSITokenizerAuthenticateMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerAuthenticateParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Authenticate(ctx, parameters.Token)
}

type meshPRSITokenizerRefreshMPS struct {
	service prsim.Tokenizer
}

func (that *meshPRSITokenizerRefreshMPS) Att() *macro.Att {
	return &macro.Att{Name: strings.ReplaceAll("mesh.oauth2.refresh", "${mesh.name}", tool.Name.Get())}
}
func (that *meshPRSITokenizerRefreshMPS) Stt() *macro.Stt {
	return &macro.Stt{Name: strings.ReplaceAll("mesh.oauth2.refresh", "${mesh.name}", tool.Name.Get())}
}

func (that *meshPRSITokenizerRefreshMPS) Call(ctx context.Context, proxy interface{}, method macro.Inspector, args ...interface{}) (interface{}, error) {
	parameters := new(proxympx.MeshTokenizerRefreshParameters)
	parameters.SetArguments(ctx, args...)
	return that.service.Refresh(ctx, parameters.Token)
}

func (that *meshPRSITokenizerRefreshMPS) Invoke(ctx context.Context, invocation mpc.Invocation) (interface{}, error) {
	parameters, ok := invocation.GetParameters().(*proxympx.MeshTokenizerRefreshParameters)
	if !ok {
		return nil, cause.CompatibleError("Service %s parameters can't compatible. ", mpc.ContextWith(ctx).GetUrn())
	}
	return that.service.Refresh(ctx, parameters.Token)
}
